services:
  # --- WORKER - PYTHON ---
  cdc:
    build: ./worker
    container_name: cdc
    restart: on-failure
    # Fichero de configuración: inventory.customers.yml
    command: [ "python", "src/cdc.py", "inventory.customers.yml", "kafka:9092" ]
    volumes:
      - ./worker:/cdc
    depends_on:
      kafka:
        condition: service_started
      mysql:
        condition: service_healthy
      clickhouse:
        condition: service_healthy

  # --- MYSQL - ORIGEN ---
  mysql:
    platform: linux/amd64
    image: quay.io/debezium/example-mysql:3.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pdebezium" ]
      interval: 5s
      timeout: 5s
      retries: 10

  # --- CLICKHOUSE - DESTINO ---
  clickhouse:
    image: clickhouse/clickhouse-server:25.3
    container_name: clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      - CLICKHOUSE_DB=inventory      # Coincide con tu inventory.customers.yml
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- ZOOKEEPER (necesario para Kafka) ---
  zookeeper:
    image: quay.io/debezium/zookeeper:3.0
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  # --- KAFKA BROKER ---
  kafka:
    image: quay.io/debezium/kafka:3.0
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  # --- DEBEZIUM SERVER ---
  debezium:
    platform: linux/amd64
    image: quay.io/debezium/server:3.0
    container_name: debezium
    ports:
      - 8080:8080
    depends_on:
      kafka:
        condition: service_started
      mysql:
        condition: service_healthy
    volumes:
      # Debezium guardará aquí su memoria
      - ./worker/config:/debezium/config
      - ./worker/data:/debezium/data

  # --- KAFKA UI ---
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - 8085:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092